version: '3.1'

services:

  db:
    container_name: talezon_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TEMQUESERMUITOFORTETALAO
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  node:
    container_name: talezon_api
    image: node
    restart: always
    ports:
      - 3001:3001
    tty: true
    stdin_open: true
    command: bash
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
